name: Execução de Testes Automatizados

on:
  push:
    branches: [ main ]
    
jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar Dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Executar Testes com Robot Framework
      run: |
        robot -d ./results
