name: Execução de Testes Automatizados

on:
  push:
    branches: [ main ]
    
jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar Dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Executar Testes com Robot Framework
      run: |
        robot -d ./results api_tests/tests/

    - name: Upload dos Resultados
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: results
        path: ./results
        if-no-files-found: warn
        retention-days: 2

    - name: Download Tests Results
      if: always()
      uses: actions/download-artifact@v4
      with:
        name: results

    - name: Send Report
      if: always()
      uses: joonvena/robotframework-reporter-action@v2.1
      with:
        report_path: results
        gh_access_token: ${{ secrets.GITHUB_TOKEN }}
        show_passed_tests: false

